"""SeedContract — generated by APWorld, loaded by the Python client.

This is the immutable blueprint for a specific seed + slot.
It contains every item/location/gate definition the client needs,
plus the generation options that produced them.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import FrozenSet, Mapping

from .ids import (
    AbilityId,
    CityId,
    CollectibleId,
    CollectibleTier,
    CosmeticId,
    EventId,
    GateId,
    ItemId,
    LocationId,
    PartCategoryId,
    PartId,
    VehicleCategory,
    VehicleClass,
    VehicleId,
)
from .model import (
    CheckGranularity,
    CollectibleDefinition,
    EventDefinition,
    GateDecisionType,
    GoalDefinition,
    ItemClassification,
    ItemDefinition,
    LocationDefinition,
    PartDefinition,
    TrapDefinition,
    VehicleDefinition,
    VehicleItemMode,
)


# ═══════════════════════════════════════════════════════════════════════════════
#  Options
# ═══════════════════════════════════════════════════════════════════════════════

class ProgressionMode(str, Enum):
    CAREER = "career"
    FULL = "full"
    CHAOS = "chaos"


class PartItemization(str, Enum):
    TIERS = "tiers"
    CATEGORIES = "categories"
    INDIVIDUAL = "individual"


class VanillaRewardPolicy(str, Enum):
    SUPPRESS_AP_CONTROLLED = "suppress_ap_controlled"
    ALLOW_COSMETIC = "allow_cosmetic"
    VANILLA = "vanilla"


class GarageSlotLogic(str, Enum):
    NORMAL = "normal"            # 30 slots, no extra
    PROGRESSIVE = "progressive"  # start small, earn slots
    UNLIMITED = "unlimited"      # garage limit disabled


class StartingCityPolicy(str, Enum):
    SAN_DIEGO = "san_diego"
    RANDOMIZED = "randomized"


class StartingVehiclePolicy(str, Enum):
    CHOOSE_D = "choose_d"
    RANDOMIZED_D = "randomized_d"
    FULLY_RANDOM = "fully_random"
    NONE = "none"


@dataclass(frozen=True)
class MC3Options:
    progression_mode: ProgressionMode = ProgressionMode.CAREER
    vehicle_itemization: VehicleItemMode = VehicleItemMode.PERMITS_ONLY
    part_itemization: PartItemization = PartItemization.CATEGORIES
    collectible_checks: bool = True
    collectible_reward_randomization: bool = True
    cosmetic_checks: bool = False
    money_checks: bool = False
    tournament_granularity: CheckGranularity = CheckGranularity.COMPLETION
    club_granularity: CheckGranularity = CheckGranularity.COMPLETION
    vanilla_reward_policy: VanillaRewardPolicy = VanillaRewardPolicy.SUPPRESS_AP_CONTROLLED
    trap_percentage: int = 10               # 0-100
    garage_slot_logic: GarageSlotLogic = GarageSlotLogic.NORMAL
    starting_city_policy: StartingCityPolicy = StartingCityPolicy.SAN_DIEGO
    starting_vehicle_policy: StartingVehiclePolicy = StartingVehiclePolicy.CHOOSE_D


# ═══════════════════════════════════════════════════════════════════════════════
#  Gate definitions
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass(frozen=True)
class GateDefinition:
    """Declares what a player needs to unlock something.

    used by:
      - APWorld's set_rules() for access rules
      - the Python reducer to compute DesiredGameState
      - the payload's gate_eval() to enforce in real-time
    """
    gate_id: GateId
    description: str
    required_items: FrozenSet[str] = field(default_factory=frozenset)
    required_any: tuple[FrozenSet[str], ...] = ()   # at least one set must be satisfied
    required_counts: Mapping[str, int] = field(default_factory=dict)  # item_name → count
    required_locations: FrozenSet[str] = field(default_factory=frozenset)


@dataclass(frozen=True)
class GateDecision:
    allowed: bool
    reason_code: int = 0
    missing_gate_id: str = ""


# ═══════════════════════════════════════════════════════════════════════════════
#  SeedContract
# ═══════════════════════════════════════════════════════════════════════════════

@dataclass(frozen=True)
class SeedContract:
    schema_version: int = 1
    game: str = "Midnight Club 3: DUB Edition Remix"
    expected_serial: str = "SLUS-21355"
    expected_crc: int = 0x60A42FF5
    seed_name: str = ""
    slot: int = 1
    slot_name: str = ""
    catalog_hash: str = ""

    item_table: Mapping[ItemId, ItemDefinition] = field(default_factory=dict)
    location_table: Mapping[LocationId, LocationDefinition] = field(default_factory=dict)
    event_table: Mapping[EventId, EventDefinition] = field(default_factory=dict)
    collectible_table: Mapping[CollectibleId, CollectibleDefinition] = field(default_factory=dict)
    vehicle_table: Mapping[VehicleId, VehicleDefinition] = field(default_factory=dict)
    part_table: Mapping[PartId, PartDefinition] = field(default_factory=dict)
    gate_table: Mapping[GateId, GateDefinition] = field(default_factory=dict)
    goal_definition: GoalDefinition = field(default_factory=GoalDefinition)
    options: MC3Options = field(default_factory=MC3Options)

    def item_ids(self) -> FrozenSet[ItemId]:
        return frozenset(self.item_table.keys())

    def location_ids(self) -> FrozenSet[LocationId]:
        return frozenset(self.location_table.keys())

    def progression_item_names(self) -> FrozenSet[str]:
        return frozenset(
            it.name for it in self.item_table.values()
            if it.classification == ItemClassification.PROGRESSION
        )